[graph]
exclude-unpublished = true

[advisories]
unmaintained = "none"
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
		"CC0-1.0",
		"ISC",
		"MIT",
    "Apache-2.0",
    "BSD-3-Clause",
		"MPL-2.0",
    "Unicode-3.0",
		"CDLA-Permissive-2.0",
		# Pull by rustls ecosystem aws-lc-sys
		"OpenSSL",
]

[bans]
multiple-versions = "deny"
highlight = "all"
skip-tree = [
    # syn 1/2 is common during transition
    { name = "syn" },
		# bitflags 1/2 is common too
		{ name = "bitflags" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-git = []
